name: Terraform Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write          # GitHub OIDC token
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

env:
  TF_VERSION: 1.5.7
  YC_CLOUD_ID:  ${{ secrets.YANDEX_CLOUD_ID }}
  YC_FOLDER_ID: ${{ secrets.YANDEX_FOLDER_ID }}
  TF_BUCKET:    chistologic-tfstate
  TF_STATE_KEY: ${{ github.ref == 'refs/heads/main' && 'prod/terraform.tfstate' || format('pr/terraform-{0}.tfstate', github.head_ref) }}
  AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
# ──────────────────────────────────────────────────────────────────────────────
  fmt-validate:
    name: Fmt & Validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: YC OIDC Auth
        id: yc-auth
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id:        ${{ vars.YC_SA_ID }}
          yc-federation-id:${{ vars.YC_FEDERATION_ID }}

      - name: Init (no backend)
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
        run: terraform init -backend=false

      - name: Terraform fmt
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
        run: terraform fmt -check

      - name: Terraform validate
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
        run: terraform validate

# ──────────────────────────────────────────────────────────────────────────────
  plan:
    name: Plan
    needs: fmt-validate
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    outputs:
      has-changes: ${{ steps.plan.outputs.has-changes }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: YC OIDC Auth
        id: yc-auth
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id:        ${{ vars.YC_SA_ID }}
          yc-federation-id:${{ vars.YC_FEDERATION_ID }}

      - name: Terraform Init (S3 backend)
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
        run: |
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${TF_STATE_KEY}" \
            -backend-config="endpoint=https://storage.yandexcloud.net" \
            -backend-config="region=ru-central1" \
            -backend-config="skip_region_validation=true" \
            -backend-config="skip_credentials_validation=true"

      - id: plan
        name: Terraform Plan
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
        run: |
          terraform plan -detailed-exitcode \
            -out=tfplan.bin \
            -var cloud_id=$YC_CLOUD_ID \
            -var folder_id=$YC_FOLDER_ID || true
          echo "has-changes=$([ $? -eq 2 ] && echo true || echo false)" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan.bin
          retention-days: 7

# ──────────────────────────────────────────────────────────────────────────────
  apply:
    name: Apply (prod only)
    needs: plan
    if: needs.plan.outputs.has-changes == 'true' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: YC OIDC Auth
        id: yc-auth
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id:        ${{ vars.YC_SA_ID }}
          yc-federation-id:${{ vars.YC_FEDERATION_ID }}

      - uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform

      - name: Terraform Apply
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
        run: terraform apply -auto-approve tfplan.bin
