name: terraform

on:
  push:
    branches: [main]
  pull_request:

env:
  TF_VERSION: 1.5.7
  TF_BUCKET: ${{ vars.TF_BUCKET }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get Yandex Cloud IAM token
        id: yc-auth
        uses: docker://ghcr.io/yc-actions/yc-iam-token-fed:1.0.0
        with:
          yc-sa-id:        ${{ vars.YC_SA_ID }}
          yc-federation-id: ${{ vars.YC_FEDERATION_ID }}

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${GITHUB_REF_NAME}.tfstate" \
            -backend-config="endpoint=https://storage.yandexcloud.net" \
            -backend-config="region=ru-central1" \
            -backend-config="skip_region_validation=true" \
            -backend-config="skip_credentials_validation=true"
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -input=false -auto-approve
        env:
          YC_TOKEN: ${{ steps.yc-auth.outputs.token }}
